//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineQuebec.Windows.Ressources.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CineQuebec.Windows.Ressources.i18n.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acteurs :.
        /// </summary>
        public static string admin_ajout_acteurs_film {
            get {
                return ResourceManager.GetString("admin.ajout_acteurs_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string admin_ajout_annuler_film {
            get {
                return ResourceManager.GetString("admin.ajout_annuler_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie :.
        /// </summary>
        public static string admin_ajout_categorie_film {
            get {
                return ResourceManager.GetString("admin.ajout_categorie_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de sortie :.
        /// </summary>
        public static string admin_ajout_date_sorti_film {
            get {
                return ResourceManager.GetString("admin.ajout_date_sorti_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durée :.
        /// </summary>
        public static string admin_ajout_duree_film {
            get {
                return ResourceManager.GetString("admin.ajout_duree_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string admin_ajout_enregistrer_film {
            get {
                return ResourceManager.GetString("admin.ajout_enregistrer_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un film à l&apos;affiche.
        /// </summary>
        public static string admin_ajout_film {
            get {
                return ResourceManager.GetString("admin.ajout_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affiche du film :.
        /// </summary>
        public static string admin_ajout_image_film {
            get {
                return ResourceManager.GetString("admin.ajout_image_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir....
        /// </summary>
        public static string admin_ajout_parcourir_film {
            get {
                return ResourceManager.GetString("admin.ajout_parcourir_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réalisateurs :.
        /// </summary>
        public static string admin_ajout_realisateurs_film {
            get {
                return ResourceManager.GetString("admin.ajout_realisateurs_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre du film :.
        /// </summary>
        public static string admin_ajout_titre_film {
            get {
                return ResourceManager.GetString("admin.ajout_titre_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films.
        /// </summary>
        public static string admin_films {
            get {
                return ResourceManager.GetString("admin.films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abonnés.
        /// </summary>
        public static string admin_menu_abonnes {
            get {
                return ResourceManager.GetString("admin.menu_abonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string admin_menu_accueil {
            get {
                return ResourceManager.GetString("admin.menu_accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se déconnecter.
        /// </summary>
        public static string admin_menu_deconnection {
            get {
                return ResourceManager.GetString("admin.menu_deconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprogrammer un film.
        /// </summary>
        public static string admin_reprog_film {
            get {
                return ResourceManager.GetString("admin.reprog_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateurs.
        /// </summary>
        public static string admin_users {
            get {
                return ResourceManager.GetString("admin.users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir la liste des abonnés.
        /// </summary>
        public static string admin_visualiser_abonnes {
            get {
                return ResourceManager.GetString("admin.visualiser_abonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciné Québec.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string connexion_connect {
            get {
                return ResourceManager.GetString("connexion.connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe :.
        /// </summary>
        public static string connexion_password {
            get {
                return ResourceManager.GetString("connexion.password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur :.
        /// </summary>
        public static string connexion_username {
            get {
                return ResourceManager.GetString("connexion.username", resourceCulture);
            }
        }
    }
}
