//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CineQuebec.Windows.Ressources.i18n {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CineQuebec.Windows.Ressources.i18n.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Films déjà vu.
        /// </summary>
        public static string abonne_afficher_films_assites {
            get {
                return ResourceManager.GetString("abonne.afficher_films_assites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Acteurs :.
        /// </summary>
        public static string admin_ajout_acteurs_film {
            get {
                return ResourceManager.GetString("admin.ajout_acteurs_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string admin_ajout_annuler_film {
            get {
                return ResourceManager.GetString("admin.ajout_annuler_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie :.
        /// </summary>
        public static string admin_ajout_categorie_film {
            get {
                return ResourceManager.GetString("admin.ajout_categorie_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de sortie :.
        /// </summary>
        public static string admin_ajout_date_sorti_film {
            get {
                return ResourceManager.GetString("admin.ajout_date_sorti_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description :.
        /// </summary>
        public static string admin_ajout_description_film {
            get {
                return ResourceManager.GetString("admin.ajout_description_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée (minutes) :.
        /// </summary>
        public static string admin_ajout_duree_film {
            get {
                return ResourceManager.GetString("admin.ajout_duree_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        public static string admin_ajout_enregistrer_film {
            get {
                return ResourceManager.GetString("admin.ajout_enregistrer_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un film à l&apos;affiche.
        /// </summary>
        public static string admin_ajout_film {
            get {
                return ResourceManager.GetString("admin.ajout_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Affiche du film :.
        /// </summary>
        public static string admin_ajout_image_film {
            get {
                return ResourceManager.GetString("admin.ajout_image_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parcourir....
        /// </summary>
        public static string admin_ajout_parcourir_film {
            get {
                return ResourceManager.GetString("admin.ajout_parcourir_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réalisateurs :.
        /// </summary>
        public static string admin_ajout_realisateurs_film {
            get {
                return ResourceManager.GetString("admin.ajout_realisateurs_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre du film :.
        /// </summary>
        public static string admin_ajout_titre_film {
            get {
                return ResourceManager.GetString("admin.ajout_titre_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Films.
        /// </summary>
        public static string admin_films {
            get {
                return ResourceManager.GetString("admin.films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gérer les films et projections.
        /// </summary>
        public static string admin_gerer_films {
            get {
                return ResourceManager.GetString("admin_gerer_films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abonnés.
        /// </summary>
        public static string admin_menu_abonnes {
            get {
                return ResourceManager.GetString("admin.menu_abonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string admin_menu_accueil {
            get {
                return ResourceManager.GetString("admin.menu_accueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Se déconnecter.
        /// </summary>
        public static string admin_menu_deconnection {
            get {
                return ResourceManager.GetString("admin.menu_deconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        public static string admin_menu_retour {
            get {
                return ResourceManager.GetString("admin_menu_retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reprogrammer un film.
        /// </summary>
        public static string admin_reprog_film {
            get {
                return ResourceManager.GetString("admin.reprog_film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateurs.
        /// </summary>
        public static string admin_users {
            get {
                return ResourceManager.GetString("admin.users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voir la liste des abonnés.
        /// </summary>
        public static string admin_visualiser_abonnes {
            get {
                return ResourceManager.GetString("admin.visualiser_abonnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ciné Québec.
        /// </summary>
        public static string app_name {
            get {
                return ResourceManager.GetString("app_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string connexion_connect {
            get {
                return ResourceManager.GetString("connexion.connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe :.
        /// </summary>
        public static string connexion_password {
            get {
                return ResourceManager.GetString("connexion.password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse courriel :.
        /// </summary>
        public static string connexion_username {
            get {
                return ResourceManager.GetString("connexion.username", resourceCulture);
            }
        }
    }
}
